#基础路径配置
base:
  base_weixin_url: https://api.weixin.qq.com
  base_phpwind_url: http://47.107.116.139
  base_demo_url: https://api.apiopen.top
#日志配置
log:
  log_name: logs_
  log_level: debug
  log_format: '[%(asctime)s] %(filename)s->%(funcName)s line:%(lineno)d [%(levelname)s] %(message)s'